#!/usr/bin/env node
/**
 * Local API monitor — a Bull-Board-style live view of API HTTP traffic.
 *
 * Runs a recording reverse proxy: point a client at this port instead of the API and
 * every call is forwarded upstream, timed, and pushed to a browser dashboard over SSE.
 *
 *   node tooling/dev/api-monitor/server.mjs
 *   PORT=4000 UPSTREAM=http://localhost:3000 node tooling/dev/api-monitor/server.mjs
 *
 * Dashboard   http://localhost:4000/
 * Proxy       http://localhost:4000/api/v1/...   ->   UPSTREAM/api/v1/...
 *
 * Dev-only. Bodies are buffered in memory (capped, ring-buffered) and Authorization /
 * Cookie values are truncated before they ever reach the browser.
 */
import http from 'node:http';
import { URL } from 'node:url';

const PORT = Number(process.env.PORT || 4000);
const UPSTREAM = process.env.UPSTREAM || 'http://localhost:3000';
const MAX_CALLS = Number(process.env.MAX_CALLS || 2000);
const MAX_BODY = Number(process.env.MAX_BODY || 24_000);

const upstream = new URL(UPSTREAM);

/** Ring buffer of recorded calls, newest last. */
const calls = [];
let seq = 0;
/**
 * Run metadata posted by the load script itself (`POST /__monitor/run`).
 *
 * The dashboard used to GUESS the command from traffic shape and got it wrong — it
 * reported `VUS=78 ITERATIONS=1` for a `VUS=100 RAMP=30s` run, because peak overlap
 * undercounts a ramp. Having the script state its own parameters is exact; inference
 * is only the fallback when something other than the scenario is driving traffic.
 */
let runMeta = null;
/** Connected dashboard clients (SSE). */
const clients = new Set();

/* ─────────────────────────── helpers ─────────────────────────── */

/** Collapse volatile path segments so stats group by route, not by instance. */
function normalizePath(pathname) {
  return pathname
    .split('/')
    .map((seg) => {
      if (/^(org|usr|ses|sub|inv|key|ntf|whk|upl|mfa|cred|exp)_[a-z0-9]+$/i.test(seg)) return ':id';
      if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(seg))
        return ':uuid';
      if (/^\d+$/.test(seg)) return ':n';
      // slugs generated by the load scenario / onboarding
      if (/^k6-org-[\w-]+$/i.test(seg)) return ':slug';
      return seg;
    })
    .join('/');
}

/** Never ship a full credential to the browser — enough to correlate, not to reuse. */
function redactHeaders(headers) {
  const out = {};
  for (const [k, v] of Object.entries(headers)) {
    const key = k.toLowerCase();
    const val = Array.isArray(v) ? v.join('; ') : String(v ?? '');
    if (key === 'authorization') {
      const m = /^Bearer\s+(.*)$/i.exec(val);
      out[k] = m
        ? `Bearer ${m[1].slice(0, 12)}…${m[1].slice(-8)} (${m[1].length} chars)`
        : '[redacted]';
    } else if (key === 'cookie' || key === 'set-cookie') {
      out[k] = val
        .split(/;\s*/)
        .map((c) => {
          const i = c.indexOf('=');
          if (i < 0) return c;
          const name = c.slice(0, i);
          const value = c.slice(i + 1);
          return value.length > 16 ? `${name}=${value.slice(0, 8)}…(${value.length})` : c;
        })
        .join('; ');
    } else {
      out[k] = val;
    }
  }
  return out;
}

function clip(buf) {
  if (!buf?.length) return { body: '', bytes: 0, truncated: false };
  const bytes = buf.length;
  const slice = buf.subarray(0, MAX_BODY).toString('utf8');
  return { body: slice, bytes, truncated: bytes > MAX_BODY };
}

function broadcast(event, payload) {
  const frame = `event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;
  for (const res of clients) {
    try {
      res.write(frame);
    } catch {
      clients.delete(res);
    }
  }
}

function record(call) {
  calls.push(call);
  if (calls.length > MAX_CALLS) calls.splice(0, calls.length - MAX_CALLS);
  broadcast('call', call);
}

/** Aggregate per normalized route+method. */
function buildStats() {
  const byKey = new Map();
  for (const c of calls) {
    const key = `${c.method} ${c.route}`;
    let s = byKey.get(key);
    if (!s) {
      s = { key, method: c.method, route: c.route, count: 0, ok: 0, err: 0, rl: 0, times: [] };
      byKey.set(key, s);
    }
    s.count += 1;
    if (c.status >= 200 && c.status < 400) s.ok += 1;
    else s.err += 1;
    if (c.status === 429) s.rl += 1;
    s.times.push(c.durationMs);
  }
  const pct = (arr, p) => {
    if (!arr.length) return 0;
    const a = [...arr].sort((x, y) => x - y);
    return a[Math.min(a.length - 1, Math.floor((p / 100) * a.length))];
  };
  return [...byKey.values()]
    .map((s) => ({
      key: s.key,
      method: s.method,
      route: s.route,
      count: s.count,
      ok: s.ok,
      err: s.err,
      rl: s.rl,
      avg: s.times.reduce((a, b) => a + b, 0) / s.times.length,
      p95: pct(s.times, 95),
      max: Math.max(...s.times),
      // Summed time across every call to this route — what avg alone hides. A cheap
      // route called 200 times can cost more than an expensive one called twice.
      total: s.times.reduce((a, b) => a + b, 0),
    }))
    .sort((a, b) => b.count - a.count);
}

/* ─────────────────────────── proxy ─────────────────────────── */

/**
 * Dedicated keep-alive agent. The default global agent proved unable to sustain ~20
 * concurrent journeys: sockets were reused after the upstream had closed them and the
 * proxy surfaced `socket hang up`, which looked exactly like an API failure and made
 * the monitor lie about the thing it exists to measure.
 */
const agent = new http.Agent({
  // keepAlive is deliberately OFF. Reused sockets are the classic source of
  // intermittent "socket hang up" in a Node proxy: the upstream closes an idle
  // connection, the agent hands that same socket to the next request, and it dies
  // mid-flight. That flakiness is fatal here, because the monitor's whole job is to
  // report on someone else's reliability — it must not invent failures of its own.
  // A fresh connection per request costs a little throughput and buys determinism.
  keepAlive: false,
  maxSockets: Number(process.env.MAX_SOCKETS || 512),
  timeout: 120_000,
});

/**
 * Hop-by-hop headers are per-connection and must never be forwarded (RFC 9110 §7.6.1).
 * Passing the client's `connection` / `keep-alive` through was corrupting the upstream
 * connection lifecycle and is the other half of the hang-up bug above.
 */
const HOP_BY_HOP = new Set([
  'connection',
  'keep-alive',
  'proxy-authenticate',
  'proxy-authorization',
  'te',
  'trailer',
  'transfer-encoding',
  'upgrade',
]);

function forwardableHeaders(headers) {
  const out = {};
  for (const [k, v] of Object.entries(headers)) {
    if (!HOP_BY_HOP.has(k.toLowerCase())) out[k] = v;
  }
  return out;
}

function handleProxy(req, res) {
  const started = process.hrtime.bigint();
  const startedAt = new Date().toISOString();
  const reqChunks = [];

  req.on('data', (c) => {
    if (reqChunks.reduce((n, b) => n + b.length, 0) < MAX_BODY * 2) reqChunks.push(c);
  });

  req.on('end', () => {
    const reqBuf = Buffer.concat(reqChunks);
    const target = new URL(req.url, upstream);

    const proxyReq = http.request(
      {
        protocol: upstream.protocol,
        hostname: upstream.hostname,
        port: upstream.port || (upstream.protocol === 'https:' ? 443 : 80),
        method: req.method,
        path: target.pathname + target.search,
        headers: { ...forwardableHeaders(req.headers), host: upstream.host },
        agent,
      },
      (proxyRes) => {
        const resChunks = [];
        proxyRes.on('data', (c) => {
          resChunks.push(c);
        });
        proxyRes.on('end', () => {
          const resBuf = Buffer.concat(resChunks);
          const durationMs = Number(process.hrtime.bigint() - started) / 1e6;

          res.writeHead(proxyRes.statusCode || 502, forwardableHeaders(proxyRes.headers));
          res.end(resBuf);

          record({
            id: ++seq,
            startedAt,
            method: req.method,
            path: target.pathname,
            query: target.search || '',
            route: normalizePath(target.pathname),
            status: proxyRes.statusCode || 0,
            durationMs: Math.round(durationMs * 10) / 10,
            request: {
              headers: redactHeaders(req.headers),
              ...clip(reqBuf),
            },
            response: {
              headers: redactHeaders(proxyRes.headers),
              ...clip(resBuf),
            },
          });
        });
      },
    );

    proxyReq.on('error', (err) => {
      const durationMs = Number(process.hrtime.bigint() - started) / 1e6;
      if (!res.headersSent) res.writeHead(502, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ error: 'upstream_unreachable', detail: err.message }));
      record({
        id: ++seq,
        startedAt,
        method: req.method,
        path: target.pathname,
        query: target.search || '',
        route: normalizePath(target.pathname),
        status: 0,
        durationMs: Math.round(durationMs * 10) / 10,
        request: { headers: redactHeaders(req.headers), ...clip(reqBuf) },
        response: { headers: {}, body: `PROXY ERROR: ${err.message}`, bytes: 0, truncated: false },
      });
    });

    if (reqBuf.length) proxyReq.write(reqBuf);
    proxyReq.end();
  });
}

/* ─────────────────────────── server ─────────────────────────── */

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);

  if (url.pathname === '/__monitor/stream') {
    res.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
      connection: 'keep-alive',
    });
    res.write(`retry: 2000\n\n`);
    clients.add(res);
    req.on('close', () => clients.delete(res));
    return;
  }

  if (url.pathname === '/__monitor/calls') {
    const limit = Number(url.searchParams.get('limit') || 300);
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ calls: calls.slice(-limit), total: calls.length }));
    return;
  }

  if (url.pathname === '/__monitor/stats') {
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ stats: buildStats(), total: calls.length }));
    return;
  }

  if (url.pathname === '/__monitor/clear' && req.method === 'POST') {
    calls.length = 0;
    seq = 0;
    runMeta = null;
    broadcast('cleared', {});
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ ok: true }));
    return;
  }

  // The load script announces its own parameters here at setup time.
  if (url.pathname === '/__monitor/run') {
    if (req.method === 'POST') {
      const chunks = [];
      req.on('data', (c) => chunks.push(c));
      req.on('end', () => {
        try {
          runMeta = {
            ...JSON.parse(Buffer.concat(chunks).toString('utf8')),
            at: new Date().toISOString(),
          };
          broadcast('run', runMeta);
        } catch {
          /* a malformed announcement just leaves the dashboard on inference */
        }
        res.writeHead(200, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
      });
      return;
    }
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ run: runMeta }));
    return;
  }

  if (url.pathname === '/' || url.pathname === '/index.html') {
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
    res.end(DASHBOARD_HTML);
    return;
  }

  // Answer the dashboard's own favicon here. Proxying it upstream would record a
  // 404 against the API and show the browser as a "client" in the stats — noise
  // that is entirely an artifact of viewing the dashboard.
  if (url.pathname === '/favicon.ico') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Everything else is proxied upstream.
  handleProxy(req, res);
});

/**
 * Open a few upstream connections before serving traffic.
 *
 * Without this the agent's socket pool is empty, so the first burst of concurrent
 * clients each demand a fresh TCP connection at once and some fail — which showed up
 * as a whole load run failing on its first attempt and passing on every retry. Warming
 * the pool makes the first run behave like the ones after it.
 */
function warmUpstream(count = 8) {
  return Promise.all(
    Array.from(
      { length: count },
      () =>
        new Promise((resolve) => {
          const request = http.request(
            {
              protocol: upstream.protocol,
              hostname: upstream.hostname,
              port: upstream.port || 80,
              method: 'GET',
              path: '/readyz',
              agent,
            },
            (response) => {
              response.resume();
              response.on('end', resolve);
            },
          );
          request.on('error', () => resolve());
          request.end();
        }),
    ),
  );
}

server.listen(PORT, async () => {
  process.stdout.write(
    `\n  API monitor listening\n` +
      `    dashboard   http://localhost:${PORT}/\n` +
      `    proxying    http://localhost:${PORT}/api/*  ->  ${UPSTREAM}/api/*\n`,
  );
  await warmUpstream();
  process.stdout.write(`    upstream    connection pool warmed\n\n`);
});

/* ─────────────────────────── dashboard ─────────────────────────── */

const DASHBOARD_HTML = /* html */ `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>API Monitor</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800&family=Public+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap">
<style>
/* Pastel system. Every chip is a soft tint paired with a deeper shade of the SAME hue
   for its text, so the palette stays pastel without losing contrast — a pale label on
   a pale ground would be pretty and unreadable. */
:root{
  --ground:#F6F4F8;--surface:#FFFFFF;--surface-2:#EFEBF4;--ink:#3A3644;--ink-2:#565068;
  --muted:#7B7490;--faint:#A8A2B8;--rule:#E4DEEC;--rule-soft:#F0ECF6;
  --accent:#C98A9B;--accent-ink:#9E6274;--accent-soft:#F7E6EB;
  --ok:#4A8464;--ok-bg:#DCF0E4;--warn:#A07846;--warn-bg:#FBEBD8;--bad:#A96070;--bad-bg:#FBE0E4;
  --get:#4A8464;--get-bg:#DCF0E4;--post:#5A7BA8;--post-bg:#DDE7F7;--patch:#A07846;--patch-bg:#FBEBD8;
  --put:#7A66A0;--put-bg:#EAE1F5;--del:#A96070;--del-bg:#FBE0E4;
  --term-bg:#EDEAF3;--term-ink:#565068;--term-dim:#A8A2B8;--term-accent:#9E6274;--term-str:#4A8464;
  --tip-bg:#FFFFFF;--tip-ink:#565068;--tip-rule:#E4DEEC;
}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){
  --ground:#23202B;--surface:#2B2734;--surface-2:#342F3F;--ink:#E8E3F0;--ink-2:#C9C2D6;
  --muted:#9A93AA;--faint:#746D85;--rule:#3D3749;--rule-soft:#332E3E;
  --accent:#E0A6B4;--accent-ink:#EFC3CD;--accent-soft:#3D2C34;
  --ok:#9EDBB4;--ok-bg:#26402F;--warn:#E8C295;--warn-bg:#453724;--bad:#E8A8B4;--bad-bg:#452930;
  --get:#9EDBB4;--get-bg:#26402F;--post:#A9C4E8;--post-bg:#26334A;--patch:#E8C295;--patch-bg:#453724;
  --put:#C4B0E0;--put-bg:#362D48;--del:#E8A8B4;--del-bg:#452930;
  --term-bg:#262231;--term-ink:#C9C2D6;--term-dim:#746D85;--term-accent:#E0A6B4;--term-str:#9EDBB4;
  --tip-bg:#3B3548;--tip-ink:#E8E3F0;--tip-rule:#4B4459;
}}
*{box-sizing:border-box}
html,body{height:100%}
body{margin:0;background:var(--ground);color:var(--ink);
  font-family:"Public Sans",ui-sans-serif,system-ui,sans-serif;font-size:14px;
  -webkit-font-smoothing:antialiased;display:flex;flex-direction:column;overflow:hidden}

/* ── header ── */
header{display:flex;align-items:center;gap:14px;padding:11px 18px;background:var(--surface);
  border-bottom:1px solid var(--rule);flex-wrap:wrap;flex:none}
.brand{font-family:"Archivo",sans-serif;font-weight:800;font-size:16px;letter-spacing:-.01em}
.brand span{color:var(--accent)}
.live{display:inline-flex;align-items:center;gap:7px;font-family:"Archivo",sans-serif;
  font-size:10px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--muted)}
.led{width:8px;height:8px;border-radius:50%;background:var(--faint)}
.led.on{background:var(--ok);box-shadow:0 0 0 3px var(--ok-bg);animation:p 2s infinite}
@keyframes p{0%,100%{opacity:1}50%{opacity:.45}}
.spacer{flex:1}
input[type=search],select{font-family:"IBM Plex Mono",monospace;font-size:12.5px;padding:6px 10px;
  border:1px solid var(--rule);border-radius:4px;background:var(--surface);color:var(--ink);min-width:0}
input[type=search]{width:210px}
button{font-family:"Archivo",sans-serif;font-size:11px;font-weight:700;letter-spacing:.07em;
  text-transform:uppercase;padding:7px 13px;border:1px solid var(--rule);border-radius:4px;
  background:var(--surface);color:var(--ink-2);cursor:pointer}
button:hover{border-color:var(--accent);color:var(--accent)}
button.on{background:var(--accent);border-color:var(--accent);color:#fff}
button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:1px}

/* ── split ── */
main{flex:1;display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,1fr);gap:1px;
  background:var(--rule);min-height:0}
.pane{background:var(--ground);display:flex;flex-direction:column;min-height:0;min-width:0}
.pane-head{display:flex;align-items:center;gap:10px;padding:9px 15px;background:var(--surface);
  border-bottom:1px solid var(--rule);flex:none}
.pane-head h2{font-family:"Archivo",sans-serif;font-size:11px;font-weight:700;letter-spacing:.12em;
  text-transform:uppercase;margin:0;color:var(--faint)}
.scroll{overflow:auto;flex:1;min-height:0}

/* ── tables ── */
table{border-collapse:collapse;width:100%}
th{position:sticky;top:0;z-index:1;background:var(--surface-2);font-family:"Archivo",sans-serif;
  font-size:9.5px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:var(--faint);
  text-align:left;padding:8px 12px;border-bottom:1px solid var(--rule);white-space:nowrap}
th.n{text-align:right}
td{padding:6px 12px;border-bottom:1px solid var(--rule-soft);font-size:12.5px;
  background:var(--surface);vertical-align:middle}
td.n{text-align:right;font-family:"IBM Plex Mono",monospace;font-variant-numeric:tabular-nums;
  font-size:12px;white-space:nowrap;color:var(--ink)}
tr.row{cursor:pointer}
tr.row:hover td{background:var(--surface-2)}
tr.row.sel td{background:var(--surface-2);box-shadow:inset 3px 0 0 var(--accent)}
.verb{display:inline-block;font-family:"Archivo",sans-serif;font-size:9px;font-weight:700;
  letter-spacing:.06em;text-transform:uppercase;padding:2.5px 6px;border-radius:3px;min-width:42px;text-align:center}
.GET{color:var(--get);background:var(--get-bg)}.POST{color:var(--post);background:var(--post-bg)}
.PATCH{color:var(--patch);background:var(--patch-bg)}.PUT{color:var(--put);background:var(--put-bg)}
.DELETE{color:var(--del);background:var(--del-bg)}
.path{font-family:"IBM Plex Mono",monospace;font-size:12px;letter-spacing:-.012em;
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:1px;width:99%}
.st{font-family:"IBM Plex Mono",monospace;font-size:11.5px;font-weight:600;padding:2px 6px;border-radius:3px}
.st.ok{color:var(--ok);background:var(--ok-bg)}.st.warn{color:var(--warn);background:var(--warn-bg)}
.st.bad{color:var(--bad);background:var(--bad-bg)}
.good{color:var(--ok);font-weight:600}.badv{color:var(--bad);font-weight:600}
.warnv{color:var(--warn);font-weight:600}.nil{color:var(--faint)}
.bar{height:5px;background:var(--rule-soft);border-radius:3px;overflow:hidden;min-width:44px}
.bar>i{display:block;height:100%;background:var(--accent);border-radius:3px}

/* ── right pane blocks ── */
/* Sits above the command block below it, so KPI tooltips are not painted over. */
.rblock{background:var(--surface);border-bottom:1px solid var(--rule);flex:none;
  position:relative;z-index:20}
.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(104px,1fr));gap:1px;background:var(--rule-soft)}
.kpi{background:var(--surface);padding:8px 13px}
.kpi .k{font-family:"Archivo",sans-serif;font-size:8.5px;font-weight:700;letter-spacing:.12em;
  text-transform:uppercase;color:var(--faint);white-space:nowrap}
.kpi .v{font-family:"IBM Plex Mono",monospace;font-size:17px;font-weight:600;
  font-variant-numeric:tabular-nums;margin-top:1px;letter-spacing:-.02em}
.kpi .v small{font-size:10px;color:var(--muted);margin-left:2px}
.kpi .v.ok{color:var(--ok)}.kpi .v.bad{color:var(--bad)}.kpi .v.warn{color:var(--warn)}

/* ── info tooltips ── */
.info{display:inline-flex;width:12px;height:12px;border-radius:50%;
  border:1px solid var(--faint);color:var(--faint);font-size:8.5px;font-style:normal;
  align-items:center;justify-content:center;cursor:help;position:relative;
  margin-left:4px;vertical-align:middle;flex:none}
.info:before{content:"i";font-family:Georgia,"Times New Roman",serif;font-weight:700;line-height:1}
.info:hover,.info:focus{border-color:var(--accent);color:var(--accent);outline:none}
.info .tip{display:none;position:absolute;top:calc(100% + 7px);right:-4px;z-index:50;
  width:250px;padding:10px 12px;background:var(--tip-bg);color:var(--tip-ink);
  border:1px solid var(--tip-rule);
  border-radius:7px;font-family:"Public Sans",sans-serif;font-size:11.5px;font-weight:400;
  line-height:1.5;letter-spacing:0;text-transform:none;text-align:left;
  box-shadow:0 8px 24px -8px rgba(58,54,68,.28);pointer-events:none;white-space:normal}
.info .tip b{color:var(--accent-ink);font-weight:600}
.info .tip code{font-family:"IBM Plex Mono",monospace;font-size:10.5px;
  background:var(--surface-2);padding:1px 4px;border-radius:3px}
.info .tip:after,.info .tip:before{content:"";position:absolute;bottom:100%;right:8px;
  border:6px solid transparent;border-bottom-color:var(--tip-rule)}
.info .tip:after{right:9px;border-width:5px;border-bottom-color:var(--tip-bg)}
.info:hover .tip,.info:focus .tip{display:block}
th .info{margin-left:3px}
th .info .tip{right:-4px;text-transform:none}
/* Ten columns will not fit a narrow pane. Let the stats table scroll sideways
   rather than crushing the route name down to an ellipsis. */
#statsPane table{min-width:820px}
#statsPane td.path{min-width:200px;max-width:none;width:auto}

/* ── command block ── */
.cmd{background:var(--term-bg);border-bottom:1px solid var(--rule);flex:none}
.cmd-head{display:flex;align-items:center;gap:9px;padding:8px 14px;
  border-bottom:1px solid var(--rule)}
.cmd-head b{font-family:"Archivo",sans-serif;font-size:9.5px;font-weight:700;letter-spacing:.13em;
  text-transform:uppercase;color:var(--term-dim)}
.cmd-client{font-family:"IBM Plex Mono",monospace;font-size:10.5px;color:var(--term-str);
  margin-left:auto;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:210px}
.cmd pre{margin:0;padding:11px 14px;font-family:"IBM Plex Mono",monospace;font-size:11.5px;
  line-height:1.65;color:var(--term-ink);overflow-x:auto;white-space:pre}
.cmd .c{color:var(--term-dim)}.cmd .p{color:var(--term-accent);user-select:none}
.cmd .e{color:var(--term-str)}
.cmd details{border-top:1px solid var(--rule)}
.cmd summary{padding:7px 14px;font-family:"Archivo",sans-serif;font-size:9.5px;font-weight:700;
  letter-spacing:.11em;text-transform:uppercase;color:var(--term-dim);cursor:pointer;list-style:none}
.cmd summary::-webkit-details-marker{display:none}
.cmd summary:before{content:"▸ ";color:var(--term-accent)}
.cmd details[open] summary:before{content:"▾ "}
.cmd details pre{padding-top:0}

/* ── detail ── */
.detail{padding:15px;overflow:auto;flex:1;min-height:0}
.detail h3{font-family:"Archivo",sans-serif;font-size:10px;font-weight:700;letter-spacing:.12em;
  text-transform:uppercase;color:var(--faint);margin:16px 0 7px}
.detail h3:first-child{margin-top:0}
.detail .title{font-family:"IBM Plex Mono",monospace;font-size:13px;word-break:break-all;
  display:flex;gap:9px;align-items:center;flex-wrap:wrap}
.detail pre{margin:0;background:var(--surface);border:1px solid var(--rule);border-radius:4px;
  padding:10px 12px;font-family:"IBM Plex Mono",monospace;font-size:11.5px;line-height:1.55;
  color:var(--ink-2);overflow-x:auto;white-space:pre-wrap;word-break:break-word;
  max-height:270px;overflow-y:auto}
.empty{padding:36px 20px;text-align:center;color:var(--faint);font-size:13px}
.empty code{font-family:"IBM Plex Mono",monospace;background:var(--surface-2);padding:2px 6px;border-radius:3px}
@media(max-width:980px){main{grid-template-columns:1fr;grid-template-rows:1fr 1fr}body{overflow:auto}}
</style>
</head>
<body>
<header>
  <div class="brand">API <span>Monitor</span></div>
  <div class="live"><span class="led" id="led"></span><span id="livetxt">connecting</span></div>
  <div class="spacer"></div>
  <input type="search" id="q" placeholder="filter path…" aria-label="Filter by path">
  <select id="fstatus" aria-label="Filter by status">
    <option value="">all status</option><option value="2">2xx</option><option value="3">3xx</option>
    <option value="4">4xx</option><option value="5">5xx</option><option value="429">429 only</option>
  </select>
  <button id="pause">Pause</button>
  <button id="clear">Clear</button>
</header>

<main>
  <!-- LEFT: live feed -->
  <section class="pane">
    <div class="pane-head"><h2>Live feed</h2><span class="spacer"></span>
      <span class="live" id="feedcount">0 shown</span></div>
    <div class="scroll">
      <table><thead><tr>
        <th>Method</th><th>Path</th><th class="n">Status</th><th class="n">Time</th><th class="n">At</th>
      </tr></thead><tbody id="feed"></tbody></table>
      <div class="empty" id="feedempty">
        Waiting for traffic&hellip;<br><br>
        Point a client at <code>http://localhost:${PORT}/api/v1/&hellip;</code>
      </div>
    </div>
  </section>

  <!-- RIGHT: KPIs -> command -> stats / detail -->
  <section class="pane">
    <div class="pane-head"><h2 id="rightTitle">Per-route statistics</h2><span class="spacer"></span>
      <button id="tabStats" class="on">Per-route stats</button><button id="tabDetail">Call detail</button></div>

    <div class="rblock">
      <div class="kpis">
        <div class="kpi"><div class="k">calls<i class="info" tabindex="0" aria-label="What does calls mean?"><span class="tip">Every HTTP request recorded through this proxy since the last <b>Clear</b> &mdash; all statuses, successes and failures alike.</span></i></div><div class="v" id="k-total">0</div></div>

        <div class="kpi"><div class="k">ok 2xx/3xx<i class="info" tabindex="0" aria-label="What does ok mean?"><span class="tip">Requests that came back with a success or redirect status. This is <b>transport success only</b> &mdash; a 200 does not mean the step did what you wanted, just that the server answered.</span></i></div><div class="v ok" id="k-ok">0</div></div>

        <div class="kpi"><div class="k">errors<i class="info" tabindex="0" aria-label="What does errors mean?"><span class="tip">Requests that returned 4xx or 5xx, or never completed. <b>Not all are bugs</b> &mdash; the guest cold-boot <code>/auth/refresh</code> returns 403 by design, because a first-time visitor has no session to refresh.</span></i></div><div class="v" id="k-err">0</div></div>

        <div class="kpi"><div class="k">429<i class="info" tabindex="0" aria-label="What does 429 mean?"><span class="tip">Requests turned away by a rate limiter. Counted separately from errors because a 429 is the limiter <b>working</b>, not the endpoint breaking. <code>/auth/refresh</code> is capped at 30/min per IP.</span></i></div><div class="v" id="k-rl">0</div></div>

        <div class="kpi"><div class="k">avg<i class="info" tabindex="0" aria-label="What does avg mean?"><span class="tip">Mean server response time across every recorded call. Easily pulled up by a few slow outliers &mdash; always read it next to <b>p95</b>.</span></i></div><div class="v" id="k-avg">0<small>ms</small></div></div>

        <div class="kpi"><div class="k">p95<i class="info" tabindex="0" aria-label="What does p95 mean?"><span class="tip">95% of calls finished faster than this; the slowest 5% were worse. Closer to what a user actually feels than the average, because it exposes the slow tail.</span></i></div><div class="v" id="k-p95">0<small>ms</small></div></div>

        <div class="kpi"><div class="k">routes<i class="info" tabindex="0" aria-label="What does routes mean?"><span class="tip">Distinct method + route pairs seen. Volatile path segments are normalized (<code>org_a1b2</code> becomes <code>:id</code>), so one endpoint counts once no matter how many ids passed through it.</span></i></div><div class="v" id="k-routes">0</div></div>

        <div class="kpi"><div class="k">pool max<i class="info" tabindex="0" aria-label="What is pool max?"><span class="tip"><b>DATABASE_POOL_MAX</b> on the API at the time of this run &mdash; the number of Postgres connections one API process may hold. Reported by the load script, which reads it off the live API process.</span></i></div><div class="v" id="k-pool">&mdash;</div></div>

        <div class="kpi"><div class="k">journeys<i class="info" tabindex="0" aria-label="What does journeys mean?"><span class="tip">Complete walks through the flow, counted from <code>/auth/email/send-code</code> &mdash; it fires exactly once per journey. <b>This is why call counts exceed your VU count:</b> in duration or ramp mode each user loops, so 100 users produce far more than 100 journeys.</span></i></div><div class="v" id="k-journeys">0</div></div>

        <div class="kpi"><div class="k">calls / journey<i class="info" tabindex="0" aria-label="What does calls per journey mean?"><span class="tip">Recorded calls divided by journeys. The scenario has <b>16 steps</b>, so a healthy run sits near 16. Well below that means journeys are dying partway and never firing their later steps.</span></i></div><div class="v" id="k-perjourney">0</div></div>

        <div class="kpi"><div class="k">total time<i class="info" tabindex="0" aria-label="What does total time mean?"><span class="tip"><b>Wall clock.</b> From the first recorded call starting to the last one finishing &mdash; how long the whole recorded session actually took.</span></i></div><div class="v" id="k-span">0<small>s</small></div></div>

        <div class="kpi"><div class="k">api time<i class="info" tabindex="0" aria-label="What does api time mean?"><span class="tip"><b>Summed</b> duration of every call. With concurrent clients this <b>exceeds</b> total time, because work overlapped &mdash; and <code>api time / total time</code> gives you the effective concurrency.</span></i></div><div class="v" id="k-apitime">0<small>s</small></div></div>
      </div>
    </div>

    <div class="cmd" id="cmdblock">
      <div class="cmd-head"><b>Command</b><span class="cmd-client" id="cmdclient">no traffic yet</span></div>
      <pre id="cmdmain"><span class="c"># run a client through this proxy to record it</span></pre>
      <details>
        <summary>full setup</summary>
        <pre><span class="c"># 1. local infra (Postgres + Redis)</span>
<span class="p">$</span> docker compose up -d

<span class="c"># 2. API with the TEST_MODE OTP echo</span>
<span class="p">$</span> <span class="e">TEST_MODE=true</span> pnpm dev

<span class="c"># 3. this monitor (proxies :${PORT} -> ${UPSTREAM})</span>
<span class="p">$</span> node tooling/dev/api-monitor/server.mjs</pre>
      </details>
    </div>

    <div class="scroll" id="statsPane"></div>
    <div class="detail" id="detail" hidden>
      <div class="empty">Select a call in the feed to inspect its full request and response.</div>
    </div>
  </section>
</main>

<script>
const feed=document.getElementById('feed'),detail=document.getElementById('detail'),
  statsPane=document.getElementById('statsPane'),led=document.getElementById('led'),
  livetxt=document.getElementById('livetxt'),q=document.getElementById('q'),
  fstatus=document.getElementById('fstatus'),feedempty=document.getElementById('feedempty');
let all=[],selected=null,paused=false,tab='stats',runMeta=null;
const MAXROWS=400;

const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const stCls=s=>s>=500||s===0?'bad':s>=400?(s===429?'warn':'bad'):'ok';
const pretty=b=>{if(!b)return '(empty)';try{return JSON.stringify(JSON.parse(b),null,2)}catch{return b}};
const hhmmss=iso=>{const d=new Date(iso);return d.toTimeString().slice(0,8)+'.'+String(d.getMilliseconds()).padStart(3,'0')};

function passes(c){
  const t=q.value.trim().toLowerCase();
  if(t&&!(c.path+c.query).toLowerCase().includes(t))return false;
  const f=fstatus.value;
  if(!f)return true;
  if(f==='429')return c.status===429;
  return String(c.status).startsWith(f);
}

function kpis(){
  const v=all;
  const ok=v.filter(c=>c.status>=200&&c.status<400).length;
  const rl=v.filter(c=>c.status===429).length;
  const t=v.map(c=>c.durationMs).sort((a,b)=>a-b);
  const p95=t.length?t[Math.min(t.length-1,Math.floor(.95*t.length))]:0;
  const avg=t.length?t.reduce((a,b)=>a+b,0)/t.length:0;
  const err=v.length-ok;
  document.getElementById('k-total').textContent=v.length;
  document.getElementById('k-ok').textContent=ok;
  const eEl=document.getElementById('k-err');
  eEl.textContent=err; eEl.className='v'+(err?' bad':'');
  const rEl=document.getElementById('k-rl');
  rEl.textContent=rl; rEl.className='v'+(rl?' warn':'');
  document.getElementById('k-avg').innerHTML=avg.toFixed(1)+'<small>ms</small>';
  document.getElementById('k-p95').innerHTML=p95.toFixed(1)+'<small>ms</small>';
  document.getElementById('k-routes').textContent=new Set(v.map(c=>c.method+' '+c.route)).size;

  // Two different "totals", and the gap between them is the interesting part:
  //   total time = wall clock from the first call starting to the last one finishing
  //   api time   = the sum of every call's duration
  // With concurrent clients api time EXCEEDS total time (work overlapped); with one
  // sequential client they converge, and the shortfall is client-side think time.
  const starts=v.map(c=>new Date(c.startedAt).getTime());
  const span=v.length?(Math.max(...v.map((c,i)=>starts[i]+c.durationMs))-Math.min(...starts)):0;
  const apiTime=v.reduce((a,c)=>a+c.durationMs,0);
  document.getElementById('k-span').innerHTML=fmtDur(span);
  document.getElementById('k-apitime').innerHTML=fmtDur(apiTime);

  // send-code fires exactly once per journey, so counting it counts journeys —
  // and calls/journey shows at a glance whether journeys are finishing all 16 steps.
  const journeys=v.filter(c=>c.route.endsWith('/auth/email/send-code')).length;
  const per=journeys?(v.length/journeys):0;
  document.getElementById('k-journeys').textContent=journeys;
  const pj=document.getElementById('k-perjourney');
  pj.textContent=journeys?per.toFixed(1):'0';
  pj.className='v'+(journeys&&per<12?' warn':'');
}

/** Same scaling as fmtDur but without markup — for table cells. */
function fmtPlain(ms){
  if(ms<1000)return ms.toFixed(0)+' ms';
  if(ms<60000)return (ms/1000).toFixed(2)+' s';
  return Math.floor(ms/60000)+'m '+Math.round((ms%60000)/1000)+'s';
}

/** ms -> "842ms" / "3.7s" / "1m 12s", so a long recording stays readable. */
function fmtDur(ms){
  if(ms<1000)return ms.toFixed(0)+'<small>ms</small>';
  if(ms<60000)return (ms/1000).toFixed(1)+'<small>s</small>';
  const m=Math.floor(ms/60000), s=Math.round((ms%60000)/1000);
  return m+'<small>m</small> '+s+'<small>s</small>';
}

/**
 * The monitor cannot know what was typed in another terminal, so it infers the client
 * from the User-Agent of recorded traffic and shows the command that produces it.
 */
function renderCommand(){
  const el=document.getElementById('cmdmain'), who=document.getElementById('cmdclient');

  // Exact parameters announced by the load script beat anything inferred from traffic.
  if(runMeta&&runMeta.command){
    const journeys=all.filter(c=>c.route.endsWith('/auth/email/send-code')).length;
    who.textContent=runMeta.mode?('mode: '+runMeta.mode):'announced';
    document.getElementById('k-pool').textContent=runMeta.poolMax??'\u2014';
    el.innerHTML='<span class="p">$</span> '+
      esc(runMeta.command).replace(/(BASE_URL=\\S+|VUS=\\d+|RAMP=\\S+|DURATION=\\S+|ITERATIONS=\\d+)/g,
        '<span class="e">$1</span>')+
      '\\n<span class="c"># '+journeys+' journey(s), '+all.length+' API call(s) recorded</span>';
    return;
  }

  if(!all.length){
    who.textContent='no traffic yet';
    el.innerHTML='<span class="c"># run a client through this proxy to record it</span>';
    return;
  }
  // Only API traffic identifies the client under test — and prefer a tool UA over a
  // browser one, so simply having the dashboard open does not relabel the run.
  const uas=all.filter(c=>c.path.startsWith('/api/'))
    .map(c=>c.request.headers['user-agent']||'').filter(Boolean);
  const tool=uas.filter(u=>/k6|curl|postman|insomnia|node|axios/i.test(u));
  const ua=(tool.length?tool[tool.length-1]:uas[uas.length-1])||'unknown';
  who.textContent=ua.slice(0,60);
  const api=all.filter(c=>c.path.startsWith('/api/'));
  // send-code fires exactly once per journey, so it counts journeys directly.
  const journeys=api.filter(c=>c.route.endsWith('/auth/email/send-code')).length;
  // Peak overlapping requests ~= the number of simulated users, recovered from the
  // recorded start/end times rather than guessed.
  const ev=[];
  for(const c of api){
    const s=new Date(c.startedAt).getTime();
    ev.push([s,1],[s+c.durationMs,-1]);
  }
  ev.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);
  let cur=0,peak=0;
  for(const [,d] of ev){cur+=d;if(cur>peak)peak=cur}
  const vus=Math.max(1,peak);
  // 16 calls per full journey — many more than that per journey means it looped.
  const looped=journeys>0&&api.length/journeys>20;
  const mode=looped?'DURATION=1m':'ITERATIONS=1';

  el.innerHTML='<span class="p">$</span> <span class="e">BASE_URL=http://localhost:${PORT}</span> '+
    '<span class="e">VUS='+vus+'</span> <span class="e">'+mode+'</span> \\\\\\n'+
    '    k6 run src/tests/load/k6/scenarios/fe-user-journey.js\\n'+
    (journeys
      ? '<span class="c"># '+journeys+' journey(s), '+api.length+' API call(s), peak concurrency '+vus+'</span>'
      : '<span class="c"># '+api.length+' API call(s) recorded &mdash; no journey traffic yet</span>')+
    (/k6/i.test(ua)?'':'\\n<span class="c"># note: current traffic is '+esc(ua.slice(0,40))+', not k6</span>');
}

function rowHTML(c){
  return '<tr class="row'+(selected&&selected.id===c.id?' sel':'')+'" data-id="'+c.id+'">'+
    '<td><span class="verb '+c.method+'">'+c.method+'</span></td>'+
    '<td class="path" title="'+esc(c.path+c.query)+'">'+esc(c.path+c.query)+'</td>'+
    '<td class="n"><span class="st '+stCls(c.status)+'">'+(c.status||'ERR')+'</span></td>'+
    '<td class="n">'+c.durationMs.toFixed(1)+'</td>'+
    '<td class="n" style="color:var(--faint)">'+hhmmss(c.startedAt)+'</td></tr>';
}

function renderFeed(){
  const vis=all.filter(passes).slice(-MAXROWS).reverse();
  feedempty.hidden=vis.length>0;
  feed.innerHTML=vis.map(rowHTML).join('');
  document.getElementById('feedcount').textContent=vis.length+' shown';
  kpis(); renderCommand();
}

function renderDetail(){
  if(!selected){detail.innerHTML='<div class="empty">Select a call in the feed to inspect its full request and response.</div>';return}
  const c=selected, hdr=o=>Object.entries(o).map(([k,v])=>k+': '+v).join('\\n')||'(none)';
  detail.innerHTML=
    '<div class="title"><span class="verb '+c.method+'">'+c.method+'</span>'+
      '<span>'+esc(c.path+c.query)+'</span>'+
      '<span class="st '+stCls(c.status)+'">'+(c.status||'ERR')+'</span>'+
      '<span style="color:var(--faint);font-size:12px">'+c.durationMs.toFixed(1)+' ms</span></div>'+
    '<h3>Route (normalized)</h3><pre>'+esc(c.method+' '+c.route)+'</pre>'+
    '<h3>Request headers</h3><pre>'+esc(hdr(c.request.headers))+'</pre>'+
    '<h3>Request body'+(c.request.truncated?' (truncated)':'')+'</h3><pre>'+esc(pretty(c.request.body))+'</pre>'+
    '<h3>Response headers</h3><pre>'+esc(hdr(c.response.headers))+'</pre>'+
    '<h3>Response body'+(c.response.truncated?' (truncated)':'')+'</h3><pre>'+esc(pretty(c.response.body))+'</pre>';
}

async function renderStats(){
  const r=await fetch('/__monitor/stats');const {stats}=await r.json();
  if(!stats.length){statsPane.innerHTML='<div class="empty">No traffic recorded yet.</div>';return}
  // Bar encodes share of TOTAL time, not p95 — it answers "where did the time go",
  // which is the question a totals column invites.
  const grand=stats.reduce((a,s)=>a+s.total,0)||1;
  const tip=(t)=>'<i class="info" tabindex="0"><span class="tip">'+t+'</span></i>';
  statsPane.innerHTML='<table><thead><tr><th>Method</th>'+
    '<th>Route'+tip('The normalized path &mdash; ids and slugs collapse to <code>:id</code> / <code>:slug</code> so every call to one endpoint groups together.')+'</th>'+
    '<th class="n">calls'+tip('How many times this route was hit. A route the journey visits twice per lap shows double the journey count.')+'</th>'+
    '<th class="n">ok'+tip('Calls that returned 2xx or 3xx.')+'</th>'+
    '<th class="n">err'+tip('Calls that returned 4xx/5xx or failed. Includes deliberate ones, like the guest 403 on <code>/auth/refresh</code>.')+'</th>'+
    '<th class="n">429'+tip('Calls rejected by a rate limiter &mdash; the limiter working, not the endpoint failing.')+'</th>'+
    '<th class="n">avg'+tip('Mean response time for this route.')+'</th>'+
    '<th class="n">p95'+tip('95% of calls to this route were faster than this.')+'</th>'+
    '<th class="n">total'+tip('<b>Every call to this route added up.</b> A cheap route hit 200 times can cost more than an expensive one hit twice &mdash; this is the column that shows it.')+'</th>'+
    '<th style="width:64px">share'+tip('This route&rsquo;s slice of all API time. Hover a bar for the exact percentage.')+'</th>'+
    '</tr></thead><tbody>'+
    stats.map(s=>'<tr><td><span class="verb '+s.method+'">'+s.method+'</span></td>'+
      '<td class="path" title="'+esc(s.route)+'">'+esc(s.route.replace('/api/v1',''))+'</td>'+
      '<td class="n">'+s.count+'</td>'+
      '<td class="n"><span class="good">'+s.ok+'</span></td>'+
      '<td class="n">'+(s.err?'<span class="badv">'+s.err+'</span>':'<span class="nil">&middot;</span>')+'</td>'+
      '<td class="n">'+(s.rl?'<span class="warnv">'+s.rl+'</span>':'<span class="nil">&middot;</span>')+'</td>'+
      '<td class="n">'+s.avg.toFixed(1)+'</td><td class="n">'+s.p95.toFixed(1)+'</td>'+
      '<td class="n"><b>'+fmtPlain(s.total)+'</b></td>'+
      '<td><div class="bar" title="'+((s.total/grand)*100).toFixed(1)+'% of all API time">'+
        '<i style="width:'+Math.max(2,(s.total/grand)*100)+'%"></i></div></td></tr>').join('')+
    '</tbody></table>';
}

feed.addEventListener('click',e=>{
  const tr=e.target.closest('tr.row');if(!tr)return;
  selected=all.find(c=>c.id===Number(tr.dataset.id))||null;
  setTab('detail'); renderFeed(); renderDetail();
});
q.addEventListener('input',renderFeed);
fstatus.addEventListener('change',renderFeed);
document.getElementById('pause').addEventListener('click',e=>{
  paused=!paused;e.target.classList.toggle('on',paused);e.target.textContent=paused?'Resume':'Pause';
});
document.getElementById('clear').addEventListener('click',async()=>{
  await fetch('/__monitor/clear',{method:'POST'});
  all=[];selected=null;renderFeed();renderDetail();renderStats();
});
function setTab(t){
  tab=t;
  document.getElementById('tabStats').classList.toggle('on',t==='stats');
  document.getElementById('tabDetail').classList.toggle('on',t==='detail');
  statsPane.hidden=t!=='stats'; detail.hidden=t!=='detail';
  document.getElementById('rightTitle').textContent=t==='stats'?'Per-route statistics':'Request & response';
  if(t==='stats')renderStats();
}
document.getElementById('tabStats').addEventListener('click',()=>setTab('stats'));
document.getElementById('tabDetail').addEventListener('click',()=>setTab('detail'));

Promise.all([
  fetch('/__monitor/calls?limit=8000').then(r=>r.json()),
  fetch('/__monitor/run').then(r=>r.json()).catch(()=>({run:null}))
]).then(([c,r])=>{all=c.calls||[];runMeta=r.run||null;renderFeed();renderStats()});

const es=new EventSource('/__monitor/stream');
es.onopen=()=>{led.classList.add('on');livetxt.textContent='live'};
es.onerror=()=>{led.classList.remove('on');livetxt.textContent='reconnecting'};
es.addEventListener('cleared',()=>{all=[];runMeta=null;selected=null;renderFeed();renderDetail();renderStats()});
es.addEventListener('run',e=>{runMeta=JSON.parse(e.data);renderCommand()});
es.addEventListener('call',e=>{
  const c=JSON.parse(e.data);
  all.push(c);if(all.length>8000)all.shift();
  if(!paused){renderFeed();if(tab==='stats')renderStats()}
});
</script>
</body>
</html>`;
